[versions]
    minecraft = '1.21.11-rc2'
    fabric-loader = "0.18.1"
    parchment = "2025.10.12"

    fabric = "0.139.4+1.21.11"

    vampirelib = "7.2.0+build.1-1.21.5"
    owo-lib = '0.12.21+1.21.6'
    nc = '3.6.6'
    jackson = '2.14.0'

[libraries]
    minecraft = { module = 'com.mojang:minecraft', version.ref = 'minecraft' }
    fabric-loader = { module = 'net.fabricmc:fabric-loader', version.ref = 'fabric-loader' }

    fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }

    vampirelib = { module = 'io.github.vampirestudios:VampireLib-Fabric', version.ref = 'vampirelib' }
    owo-lib = { module = 'io.wispforest:owo-lib', version.ref = 'owo-lib' }
    owo-sentinel = { module = 'io.wispforest:owo-sentinel', version.ref = 'owo-lib' }