[versions]
    minecraft = '26.3-pre-1'
    fabric-loader = "0.19.5"

    fabric = "0.159.1+26.3"

    vampirelib = "7.2.0+build.1-1.21.5"
    owo-lib = '0.13.0+1.21.11'
    nc = '3.8.3'
    jackson = '2.22.2'

[libraries]
    minecraft = { module = 'com.mojang:minecraft', version.ref = 'minecraft' }
    fabric-loader = { module = 'net.fabricmc:fabric-loader', version.ref = 'fabric-loader' }

    fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }

    vampirelib = { module = 'io.github.vampirestudios:VampireLib-Fabric', version.ref = 'vampirelib' }
    owo-lib = { module = 'io.wispforest:owo-lib', version.ref = 'owo-lib' }
    owo-sentinel = { module = 'io.wispforest:owo-sentinel', version.ref = 'owo-lib' }