[versions]
    minecraft = '1.19.3'
    quilt-mappings = '1.19.3+build.18' # Latest version is available at https://lambdaurora.dev/tools/import_quilt.html
    yarn_mappings = '1.19.3+build.5'
    fabric-loader = '0.14.13' # Latest version is available at https://fabricmc.net/versions.html

    fabric_api = '0.73.2+1.19.3'

    vampirelib = "6.1.1+build.2-1.19.3"
    clothconfig = '9.0.93'
    owo-lib = '0.10.2+1.19.3'
    appleskin = 'mc1.19-2.4.0'
    libzoomer = '6c0c9d119d'
    cct = '3.0.0+1.19.3'

[libraries]
    minecraft = { module = 'com.mojang:minecraft', version.ref = 'minecraft' }
    yarn-mappings = { module = 'net.fabricmc:yarn', version.ref = 'yarn-mappings' }
    fabric-loader = { module = 'net.fabricmc:fabric-loader', version.ref = 'fabric-loader' }

    fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
    fabric_api_deprecated = { module = "net.fabricmc.fabric-api:fabric-api-deprecated", version.ref = "fabric_api" }

    vampirelib = { module = 'io.github.vampirestudios:VampireLib-Fabric', version.ref = 'vampirelib' }
    clothconfig = { module = 'me.shedaniel.cloth:cloth-config-fabric', version.ref = 'clothconfig' }
    appleskin = { module = 'squeek.appleskin:appleskin-fabric', version.ref = 'appleskin' }
    owo-lib = { module = 'io.wispforest:owo-lib', version.ref = 'owo-lib' }
    owo-sentinel = { module = 'io.wispforest:owo-sentinel', version.ref = 'owo-lib' }
    libzoomer = { module = 'com.github.EnnuiL:LibZoomer', version.ref = 'libzoomer' }

[bundles]
    fabric = ["fabric_api", "fabric_api_deprecated"]