[versions]
    minecraft = '23w17a'
    quilt_mappings = "23w16a+build.1"
    fabric_mappings = "23w17a+build.10"
    fabric-loader = "0.14.19"
    parchment = "2023.03.12"

    fabric = "0.80.0+1.20"

    vampirelib = "7.0.1+build.1-23w17a"

[libraries]
    minecraft = { module = 'com.mojang:minecraft', version.ref = 'minecraft' }
    fabric-loader = { module = 'net.fabricmc:fabric-loader', version.ref = 'fabric-loader' }

    fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }

    vampirelib = { module = 'io.github.vampirestudios:VampireLib-Fabric', version.ref = 'vampirelib' }