[versions]
    minecraft = '1.21.8'
    quilt_mappings = "1.21.8+build.1"
    fabric-loader = "0.16.14"
    parchment = "2025.07.20"

    fabric = "0.130.0+1.21.8"

    vampirelib = "7.2.0+build.1-1.21.5"
    owo-lib = '0.12.21+1.21.6'
    cct = '3.3.0+1.21'
    nc = '3.6.6'
    jackson = '2.14.0'
    accessories = '1.2.15-beta+1.21.4'

[libraries]
    minecraft = { module = 'com.mojang:minecraft', version.ref = 'minecraft' }
    fabric-loader = { module = 'net.fabricmc:fabric-loader', version.ref = 'fabric-loader' }

    fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }

    vampirelib = { module = 'io.github.vampirestudios:VampireLib-Fabric', version.ref = 'vampirelib' }
    owo-lib = { module = 'io.wispforest:owo-lib', version.ref = 'owo-lib' }
    owo-sentinel = { module = 'io.wispforest:owo-sentinel', version.ref = 'owo-lib' }
#    libzoomer = { module = 'com.github.EnnuiL:LibZoomer', version.ref = 'libzoomer' }