[versions]
    minecraft = '23w16a'
    quilt-mappings = '23w16a+build.1' # Latest version is available at https://lambdaurora.dev/tools/import_quilt.html
    fabric-loader = '0.14.19' # Latest version is available at https://fabricmc.net/versions.html

    fabric_api = '0.78.1+1.20'

    vampirelib = "7.0.0+build.1-23w16a"
    clothconfig = '10.0.96'
    owo-lib = '0.10.3+1.19.3'
    appleskin = 'mc1.19-2.4.0'
    libzoomer = '6c0c9d119d'
    cct = '3.0.0+1.19.3'

[libraries]
    minecraft = { module = 'com.mojang:minecraft', version.ref = 'minecraft' }
    fabric-loader = { module = 'net.fabricmc:fabric-loader', version.ref = 'fabric-loader' }

    fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
    fabric_api_deprecated = { module = "net.fabricmc.fabric-api:fabric-api-deprecated", version.ref = "fabric_api" }

    vampirelib = { module = 'io.github.vampirestudios:VampireLib-Fabric', version.ref = 'vampirelib' }
    clothconfig = { module = 'me.shedaniel.cloth:cloth-config-fabric', version.ref = 'clothconfig' }
    appleskin = { module = 'squeek.appleskin:appleskin-fabric', version.ref = 'appleskin' }
    owo-lib = { module = 'io.wispforest:owo-lib', version.ref = 'owo-lib' }
    owo-sentinel = { module = 'io.wispforest:owo-sentinel', version.ref = 'owo-lib' }
    libzoomer = { module = 'com.github.EnnuiL:LibZoomer', version.ref = 'libzoomer' }

[bundles]
    fabric = ["fabric_api", "fabric_api_deprecated"]