package io.github.vampirestudios.obsidian.api;

import com.google.common.collect.ImmutableMap;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.SoundType;

import java.util.Map;

public class VanillaSoundEvents {
    public static final Map<Identifier, SoundType> SOUND_TYPES = ImmutableMap.<Identifier, SoundType>builder()
            .put(Identifier.withDefaultNamespace("wood"), SoundType.WOOD)
            .put(Identifier.withDefaultNamespace("gravel"), SoundType.GRAVEL)
            .put(Identifier.withDefaultNamespace("grass"), SoundType.GRASS)
            .put(Identifier.withDefaultNamespace("lily_pad"), SoundType.LILY_PAD)
            .put(Identifier.withDefaultNamespace("stone"), SoundType.STONE)
            .put(Identifier.withDefaultNamespace("metal"), SoundType.METAL)
            .put(Identifier.withDefaultNamespace("glass"), SoundType.GLASS)
            .put(Identifier.withDefaultNamespace("wool"), SoundType.WOOL)
            .put(Identifier.withDefaultNamespace("sand"), SoundType.SAND)
            .put(Identifier.withDefaultNamespace("snow"), SoundType.SNOW)
            .put(Identifier.withDefaultNamespace("powder_snow"), SoundType.POWDER_SNOW)
            .put(Identifier.withDefaultNamespace("ladder"), SoundType.LADDER)
            .put(Identifier.withDefaultNamespace("anvil"), SoundType.ANVIL)
            .put(Identifier.withDefaultNamespace("slime"), SoundType.SLIME_BLOCK)
            .put(Identifier.withDefaultNamespace("honey"), SoundType.HONEY_BLOCK)
            .put(Identifier.withDefaultNamespace("wet_grass"), SoundType.WET_GRASS)
            .put(Identifier.withDefaultNamespace("coral"), SoundType.CORAL_BLOCK)
            .put(Identifier.withDefaultNamespace("bamboo"), SoundType.BAMBOO)
            .put(Identifier.withDefaultNamespace("bamboo_sapling"), SoundType.BAMBOO_SAPLING)
            .put(Identifier.withDefaultNamespace("scaffolding"), SoundType.SCAFFOLDING)
            .put(Identifier.withDefaultNamespace("sweet_berry_bush"), SoundType.SWEET_BERRY_BUSH)
            .put(Identifier.withDefaultNamespace("crop"), SoundType.CROP)
            .put(Identifier.withDefaultNamespace("stem"), SoundType.HARD_CROP)
            .put(Identifier.withDefaultNamespace("vine"), SoundType.VINE)
            .put(Identifier.withDefaultNamespace("nether_wart"), SoundType.NETHER_WART)
            .put(Identifier.withDefaultNamespace("lantern"), SoundType.LANTERN)
            .put(Identifier.withDefaultNamespace("nether_stem"), SoundType.STEM)
            .put(Identifier.withDefaultNamespace("nylium"), SoundType.NYLIUM)
            .put(Identifier.withDefaultNamespace("fungus"), SoundType.FUNGUS)
            .put(Identifier.withDefaultNamespace("roots"), SoundType.ROOTS)
            .put(Identifier.withDefaultNamespace("shroomlight"), SoundType.SHROOMLIGHT)
            .put(Identifier.withDefaultNamespace("weeping_vines"), SoundType.WEEPING_VINES)
            .put(Identifier.withDefaultNamespace("weeping_vines_low_pitch"), SoundType.TWISTING_VINES)
            .put(Identifier.withDefaultNamespace("soul_sand"), SoundType.SOUL_SAND)
            .put(Identifier.withDefaultNamespace("soul_soil"), SoundType.SOUL_SOIL)
            .put(Identifier.withDefaultNamespace("basalt"), SoundType.BASALT)
            .put(Identifier.withDefaultNamespace("wart_block"), SoundType.WART_BLOCK)
            .put(Identifier.withDefaultNamespace("netherrack"), SoundType.NETHERRACK)
            .put(Identifier.withDefaultNamespace("nether_bricks"), SoundType.NETHER_BRICKS)
            .put(Identifier.withDefaultNamespace("nether_sprouts"), SoundType.NETHER_SPROUTS)
            .put(Identifier.withDefaultNamespace("nether_ore"), SoundType.NETHER_ORE)
            .put(Identifier.withDefaultNamespace("bone"), SoundType.BONE_BLOCK)
            .put(Identifier.withDefaultNamespace("netherite"), SoundType.NETHERITE_BLOCK)
            .put(Identifier.withDefaultNamespace("ancient_debris"), SoundType.ANCIENT_DEBRIS)
            .put(Identifier.withDefaultNamespace("lodestone"), SoundType.LODESTONE)
            .put(Identifier.withDefaultNamespace("chain"), SoundType.CHAIN)
            .put(Identifier.withDefaultNamespace("nether_gold_ore"), SoundType.NETHER_GOLD_ORE)
            .put(Identifier.withDefaultNamespace("gilded_blackstone"), SoundType.GILDED_BLACKSTONE)
            .put(Identifier.withDefaultNamespace("candle"), SoundType.CANDLE)
            .put(Identifier.withDefaultNamespace("amethyst_block"), SoundType.AMETHYST)
            .put(Identifier.withDefaultNamespace("amethyst_cluster"), SoundType.AMETHYST_CLUSTER)
            .put(Identifier.withDefaultNamespace("small_amethyst_bud"), SoundType.SMALL_AMETHYST_BUD)
            .put(Identifier.withDefaultNamespace("medium_amethyst_bud"), SoundType.MEDIUM_AMETHYST_BUD)
            .put(Identifier.withDefaultNamespace("large_amethyst_bud"), SoundType.LARGE_AMETHYST_BUD)
            .put(Identifier.withDefaultNamespace("tuff"), SoundType.TUFF)
            .put(Identifier.withDefaultNamespace("calcite"), SoundType.CALCITE)
            .put(Identifier.withDefaultNamespace("dripstone_block"), SoundType.DRIPSTONE_BLOCK)
            .put(Identifier.withDefaultNamespace("pointed_dripstone"), SoundType.POINTED_DRIPSTONE)
            .put(Identifier.withDefaultNamespace("copper"), SoundType.COPPER)
            .put(Identifier.withDefaultNamespace("cave_vines"), SoundType.CAVE_VINES)
            .put(Identifier.withDefaultNamespace("spore_blossom"), SoundType.SPORE_BLOSSOM)
            .put(Identifier.withDefaultNamespace("azalea"), SoundType.AZALEA)
            .put(Identifier.withDefaultNamespace("flowering_azalea"), SoundType.FLOWERING_AZALEA)
            .put(Identifier.withDefaultNamespace("moss_carpet"), SoundType.MOSS_CARPET)
            .put(Identifier.withDefaultNamespace("pink_petals"), SoundType.PINK_PETALS)
            .put(Identifier.withDefaultNamespace("moss_block"), SoundType.MOSS)
            .put(Identifier.withDefaultNamespace("big_dripleaf"), SoundType.BIG_DRIPLEAF)
            .put(Identifier.withDefaultNamespace("small_dripleaf"), SoundType.SMALL_DRIPLEAF)
            .put(Identifier.withDefaultNamespace("rooted_dirt"), SoundType.ROOTED_DIRT)
            .put(Identifier.withDefaultNamespace("hanging_roots"), SoundType.HANGING_ROOTS)
            .put(Identifier.withDefaultNamespace("azalea_leaves"), SoundType.AZALEA_LEAVES)
            .put(Identifier.withDefaultNamespace("sculk_sensor"), SoundType.SCULK_SENSOR)
            .put(Identifier.withDefaultNamespace("sculk_catalyst"), SoundType.SCULK_CATALYST)
            .put(Identifier.withDefaultNamespace("sculk"), SoundType.SCULK)
            .put(Identifier.withDefaultNamespace("sculk_vein"), SoundType.SCULK_VEIN)
            .put(Identifier.withDefaultNamespace("sculk_shrieker"), SoundType.SCULK_SHRIEKER)
            .put(Identifier.withDefaultNamespace("glow_lichen"), SoundType.GLOW_LICHEN)
            .put(Identifier.withDefaultNamespace("deepslate"), SoundType.DEEPSLATE)
            .put(Identifier.withDefaultNamespace("deepslate_bricks"), SoundType.DEEPSLATE_BRICKS)
            .put(Identifier.withDefaultNamespace("deepslate_tiles"), SoundType.DEEPSLATE_TILES)
            .put(Identifier.withDefaultNamespace("polished_deepslate"), SoundType.POLISHED_DEEPSLATE)
            .put(Identifier.withDefaultNamespace("froglight"), SoundType.FROGLIGHT)
            .put(Identifier.withDefaultNamespace("frogspawn"), SoundType.FROGSPAWN)
            .put(Identifier.withDefaultNamespace("mangrove_roots"), SoundType.MANGROVE_ROOTS)
            .put(Identifier.withDefaultNamespace("muddy_mangrove_roots"), SoundType.MUDDY_MANGROVE_ROOTS)
            .put(Identifier.withDefaultNamespace("mud"), SoundType.MUD)
            .put(Identifier.withDefaultNamespace("mud_bricks"), SoundType.MUD_BRICKS)
            .put(Identifier.withDefaultNamespace("packed_mud"), SoundType.PACKED_MUD)
            .put(Identifier.withDefaultNamespace("hanging_sign"), SoundType.HANGING_SIGN)
            .put(Identifier.withDefaultNamespace("nether_wood_hanging_sign"), SoundType.NETHER_WOOD_HANGING_SIGN)
            .put(Identifier.withDefaultNamespace("bamboo_wood_hanging_sign"), SoundType.BAMBOO_WOOD_HANGING_SIGN)
            .put(Identifier.withDefaultNamespace("bamboo_wood"), SoundType.BAMBOO_WOOD)
            .put(Identifier.withDefaultNamespace("nether_wood"), SoundType.NETHER_WOOD)
            .put(Identifier.withDefaultNamespace("cherry_wood"), SoundType.CHERRY_WOOD)
            .put(Identifier.withDefaultNamespace("cherry_sapling"), SoundType.CHERRY_SAPLING)
            .put(Identifier.withDefaultNamespace("cherry_leaves"), SoundType.CHERRY_LEAVES)
            .put(Identifier.withDefaultNamespace("cherry_wood_hanging_sign"), SoundType.CHERRY_WOOD_HANGING_SIGN)
            .put(Identifier.withDefaultNamespace("chiseled_bookshelf"), SoundType.CHISELED_BOOKSHELF)
            .put(Identifier.withDefaultNamespace("suspicious_sand"), SoundType.SUSPICIOUS_SAND)
            .put(Identifier.withDefaultNamespace("suspicious_gravel"), SoundType.SUSPICIOUS_GRAVEL)
            .put(Identifier.withDefaultNamespace("decorated_pot"), SoundType.DECORATED_POT)
            .put(Identifier.withDefaultNamespace("decorated_pot_shatter"), SoundType.DECORATED_POT_CRACKED)
            .put(Identifier.withDefaultNamespace("trial_spawner"), SoundType.TRIAL_SPAWNER)
            .put(Identifier.withDefaultNamespace("sponge"), SoundType.SPONGE)
            .put(Identifier.withDefaultNamespace("wet_sponge"), SoundType.WET_SPONGE)
            .build();

    public static void init() {
        /* nothing to do */
    }

    public static SoundType get(Identifier soundType) {
        SoundType color = SOUND_TYPES.get(soundType);
        if (color == null)
            throw new IllegalStateException("No sound type known with name " + soundType);
        return color;
    }
}